
services:
  core_api:
    build: .
    container_name: core-api-container
    ports:
      - "8080:8000"  # Map host port 8000 to container port 8000
    volumes:
      - .:/app  # Mount the current directory inside the container
    environment:
      - PYTHONUNBUFFERED=1  # Ensure log output is not buffered